"""Synthetic P-01 roster source (40 residents). Ruth Alvarez is index 0 and takes
OWNER_PHONE at seed time; everyone else gets fictional +15550100XX numbers
(reserved fiction range) that must be appended to PHONE_ALLOWLIST.

Tuple shape: (name, language, age_band, lives_alone, has_ac,
powered_medical_device|None, mobility, preferred_channel, notes)
"""

ROSTER = [
    ("Ruth Alvarez", "en", "75-84", True, False, None, "independent", "sms",
     "Tier 1: 81, lives alone, no AC. Answers fast. Eval anchor."),
    ("Elena Vasquez", "es", "75-84", True, False, "oxygen concentrator", "limited", "sms",
     "Tier 1: on oxygen concentrator, power-dependent. Medical priority."),
    ("Walter Briggs", "en", "85+", True, True, None, "independent", "call",
     "Only answers voice calls, never texts. Son in Springdale."),
    ("Mabel Thornton", "en", "85+", False, True, None, "walker", "sms",
     "Replies 'fine' to everything, even when she is not. Eval case."),
    ("Jorge Mendez", "es", "65-74", False, True, None, "independent", "sms",
     "Lives with wife Rosa. Handy, checks on neighbors himself."),
    ("Dorothy Gaines", "en", "75-84", True, False, None, "independent", "sms",
     "Tier 1: no AC, proud, slow to admit need. Daughter calls Sundays."),
    ("Samuel Okafor", "en", "65-74", False, True, None, "independent", "sms",
     "Retired teacher. Diabetic, keeps insulin cool with ice packs."),
    ("Lucia Fernandez", "es", "85+", True, True, None, "wheelchair", "sms",
     "Wheelchair user, aide visits mornings. Grandson nearby."),
    ("Harold Finch", "en", "75-84", True, True, "cpap", "independent", "sms",
     "CPAP at night. Hard of hearing, texts in caps."),
    ("Betty Lou Carson", "en", "75-84", False, False, None, "independent", "sms",
     "No AC but sister next door has. Shares a box fan."),
    ("Rafael Torres", "es", "65-74", True, True, None, "independent", "sms",
     "Night-shift janitor, sleeps days. Text after 2pm only."),
    ("Agnes Kowalski", "en", "85+", True, False, None, "walker", "call",
     "Tier 1: no AC, walker, prefers calls. Church friend checks Fridays."),
    ("Tom Becker", "en", "65-74", False, True, None, "independent", "sms",
     "Veteran, plays dominoes at the center. Calm in a crisis."),
    ("Maria Santos", "es", "75-84", True, True, None, "independent", "sms",
     "Widow, two cats. Niece in Rogers holds a spare key."),
    ("Earl Dobbins", "en", "75-84", True, False, None, "independent", "sms",
     "Tier 1: no AC, fixed income, refuses help twice before accepting."),
    ("Consuelo Reyes", "es", "65-74", False, True, None, "independent", "sms",
     "Bakes for the block. Will shelter neighbors before herself."),
    ("Frank Delaney", "en", "85+", False, True, "nebulizer", "limited", "sms",
     "Nebulizer treatments twice daily. Wife Helen manages meds."),
    ("Helen Delaney", "en", "85+", False, True, None, "limited", "sms",
     "Frank's wife. Forgetful; confirm with Frank on medical answers."),
    ("Patsy Nguyen", "en", "65-74", True, True, None, "independent", "sms",
     "Gardener, out back mornings. Texts with photos."),
    ("Domingo Cruz", "es", "75-84", True, False, None, "independent", "sms",
     "Tier 1: no AC, tiny house on Willow. Drinks little water, remind him."),
    ("Virginia Hall", "en", "75-84", False, True, None, "independent", "sms",
     "Lives with brother. Quilter, always home afternoons."),
    ("Raymond Hall", "en", "75-84", False, True, None, "independent", "call",
     "Virginia's brother. Answers for both, prefers calls."),
    ("Isabel Moreno", "es", "85+", True, True, None, "walker", "sms",
     "Speaks little English; daughter translates evenings."),
    ("Clifford Moss", "en", "65-74", True, True, None, "independent", "sms",
     "Truck driver, home weekends. Dog named Biscuit."),
    ("Rosa Jimenez", "es", "65-74", False, True, None, "independent", "sms",
     "Jorge's wife. Keeps the family phone charged."),
    ("Edith Plumlee", "en", "85+", True, False, None, "limited", "sms",
     "Tier 1: no AC, limited mobility, upstairs bedroom. Move downstairs in heat."),
    ("Norman Tate", "en", "75-84", False, True, "cpap", "independent", "sms",
     "CPAP user. Plays chess by mail. Dry humor."),
    ("Alma Gutierrez", "es", "75-84", True, True, None, "independent", "sms",
     "Church choir. Will ask for prayer before answering questions."),
    ("Cecil Ward", "en", "65-74", True, False, None, "independent", "sms",
     "Tier 2: no AC but healthy and stubborn. Check once, then leave be."),
    ("Blanca Ortiz", "es", "75-84", False, True, None, "walker", "sms",
     "Walker, ground floor. Son drives her to the center."),
    ("Vernon Pike", "en", "85+", True, True, None, "independent", "call",
     "Prefers calls, tells long stories. Has AC, low risk, high talk."),
    ("Della Ramey", "en", "75-84", True, False, None, "independent", "sms",
     "Tier 1: no AC, keeps windows shut for safety. Remind to ventilate."),
    ("Hector Salazar", "es", "65-74", False, True, None, "independent", "sms",
     "Mechanic, fixes the center's van. Strong network on his street."),
    ("Opal Sargent", "en", "85+", False, True, None, "limited", "sms",
     "Lives with granddaughter Kayla (17), home after school."),
    ("Felipe Navarro", "es", "75-84", True, True, "oxygen concentrator", "limited", "sms",
     "Second oxygen user. Backup tanks in closet, check count."),
    ("Gertie Hobbs", "en", "75-84", True, True, None, "independent", "sms",
     "New to the roster, shy. Sister in Bella Vista."),
    ("Anselmo Vega", "es", "65-74", True, False, None, "independent", "sms",
     "Tier 2: no AC, works yard jobs, out all day. Evenings best."),
    ("Lena Whitfield", "en", "75-84", False, True, None, "independent", "sms",
     "Book club host. Will relay messages to three neighbors."),
    ("Cristobal Luna", "es", "85+", True, True, None, "walker", "call",
     "Walker, prefers calls. Naps 1-3pm, avoid those hours."),
    ("Pearl Ashford", "en", "85+", True, False, None, "limited", "sms",
     "Tier 1: no AC, limited mobility. Emergency contact is neighbor Tom."),
]
